export const SET_SOURCE = "SET_SOURCE";
export const SET_DESTINATION = "SET_DESTINATION";
export const SET_WAYPOINT = "SET_WAYPOINT";
export const REMOVE_WAYPOINT = "REMOVE_WAYPOINT";
export const EMPTY_WAYPOINTS = "EMPTY_WAYPOINTS";
