export const SET_CURRENT_USER_JWT = "SET_CURRENT_USER_JWT";
export const SET_CURRENT_USER_IMG_URL = "SET_CURRENT_USER_IMG_URL";
export const SET_CURRENT_USER_NAME = "SET_CURRENT_USER_NAME";
export const RESET_CURRENT_USER = "RESET_CURRENT_USER";
